# Generated by Django 4.2.7 on 2023-11-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='telefono',
        ),
    ]
